Signal_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),

]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('hello/', views.hello),
    path('', views.register, name='register') ,
    path('profile/', views.profile, name='profile'),
    path('login/', views.LoginView.as_view() , name="login"),

]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
 
    def __str__(self):
        return f'{self.user.username} Profile'

app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
 
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
 

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
 
    class Meta:
        model = User
        fields = ['username', 'email']
 
 
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class Loginform(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email","password",)

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic.edit import CreateView

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .forms import Loginform
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

# Create your views here.


def hello(request):
    return HttpResponse("hiii")


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})


class LoginView(CreateView):
    form_class = Loginform
    template_name = "login.html"
    context_object_name = 'loginhere'
    success_url = reverse_lazy('app:login')

    def post(self, request):
        email = request.POST.get('email')
        user = User.objects.filter(email=email)
        if user:
            return redirect("/app/profile/")
        else:
            return HttpResponse("Invalid User")





@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and  p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)



    context =  {
        'u_form' :  u_form,
        'p_form': p_form
    }

    return render(request,"profile.html",context)

app/templates/login.html
<!-- {% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }} alert-dismissible">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %} -->

<div style="background-color: bisque;" >
    <center><br>
        <h1 style="font:bold; color:blue">Login Here!</h1> <br><br>

        <div>
            <form method="POST" action="{% url 'app:login' %}" style="width:400px;">
                {% csrf_token %}
                {{form.as_p}} <br>
                <button type="submit" class="btn btn-danger">Login</button>

            </form>
        </div>
    </center>
</div>

app/templates/profile.html
<div style="background-color: bisque; height:max-content">

    <center>
         <div>
            <form action="{% url 'app:profile' %}" method="POST" style="width: 300px; height:1000px;">
                {% csrf_token %}
    
                <br>
                <h2>Update profile</h2>  <br><br>
    
                {{form}} <br><br>
                <button type="submit" class="btn btn-danger">Update</button>
    
            </form>
        </div>
    
    </center>
    </div>
    

app/templates/register.html
<div style="background-color: bisque; height:max-content">

<center>
     <div>
        <form action="" method="POST" style="width: 300px; height:1000px;">
            {% csrf_token %}

            <br>
            <h2>SignUp</h2>  <br><br>

            {{form.as_p}} <br>
            <button type="submit" class="btn btn-danger">SignUp</button>

        </form>
    </div>

</center>
</div>